Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -96,7 +96,6 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-
   DeployInfraAndBuild:
     name: Deploy Infra and Build
     needs: EditAppDeployFile
@@ -138,3 +137,50 @@ jobs:
           terraform fmt
           terraform plan -var-file=variables.tfvars
           terraform apply -auto-approve -var-file=variables.tfvars
+      
+      - name: Output ACR Server
+        working-directory: Terraform/Part2
+        run: |
+          acr_login_server=$(terraform output -raw acr_login_server)
+          if [ -z "$acr_login_server" ]; then
+            echo "Error: acr_login_server string is empty!"
+            exit 1
+          fi
+          echo "$acr_login_server" > acr_login_server.txt
+
+      - name: Upload Acr Login Server as artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: acr_login_server
+          path: |
+            ./Terraform/Part2/acr_login_server.txt
+        
+  DeployImageForAKS:
+    name: Build Image for AKS
+    needs: DeployInfraAndBuild
+    runs-on: ubuntu-latest
+    steps:
+      - name: Code Checkout
+        uses: actions/checkout@v4
+
+      - name: Log in to Azure
+        uses: azure/login@v1
+        with:
+          client-id: ${{ secrets.SP_CLIENT_ID }}
+          tenant-id: ${{ secrets.TENANT_ID }}
+          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
+
+      - name: Azure CLI script
+        uses: azure/cli@v2
+        with:
+          azcliversion: latest
+          inlineScript: |
+            az account show
+            az storage -h
+          
+      - name: Build and Upload Docker Image for Deploy
+        run: |
+          ACR_REGISTRY=$(cat ../acr_login_server.txt)
+          az acr login --name ${{ secrets.ACR_NAME }}
+          docker build -t $ACR_REGISTRY/azure-function:latest .
+          docker push $ACR_REGISTRY/azure-function:latest
